name: Greetings

on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.MY_GITHUB_API }}
          issue-message: "Hello @${{ github.actor }}, thanks for opening a issue, your contribution is valuable to us. The project admin.s will review this issue and come back to you as soon as possible."
          pr-message: "Hello @${{ github.actor }}, thanks for rising a Pull request, your contribution is valuable to us. The admin.s will review this Pull Request or merge it polishly as soon as possible. Keep the great work up!"
